/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lost_pet.app;

import lost_pet.list.LinkedList;

import static lost_pet.utilities.StringUtils.join;
import static lost_pet.utilities.StringUtils.split;
import static lost_pet.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
